services:
  nats:
    image: nats:2.10
    container_name: "nats"

  redis:
    image: redis:6-alpine
    container_name: "redis"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "chat_server"
    depends_on:
      - nats
      - redis
    ports:
      - "8080:8080"
    volumes:
      - "./config.json:/app/config.json"
