services:
  nats:
    image: nats:2.9-alpine
    container_name: "nats"
    ports:
      - "4222:4222"
      - "8222:8222"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "chat_server"
    depends_on:
      - nats
    ports:
      - "8080:8080"
    volumes:
      - "./config.json:/app/config.json"
