services:
  nats:
    image: nats:2.10
    container_name: "nats"
    ports:
      - "127.0.0.1:4222:4222"
      - "127.0.0.1:8222:8222"

  redis:
    image: redis/redis-stack:latest
    container_name: "redis"
    ports:
      - "127.0.0.1:7379:6379"
      - "127.0.0.1:8001:8001"
    volumes:
      - redis-dev-volume:/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: "server_dev"
    depends_on:
      - nats
      - redis
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - "./config.json:/app/config.json"
    environment:
      - AIR_ENV=dev

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    depends_on:
      - server_logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"

  server_logs:
    container_name: server_dev_logs
    image: alpine
    depends_on:
      - server
    volumes:
      - ./logs:/var/logs
    command: "tail -f /var/logs/server.log"
    network_mode: none
    restart: unless-stopped

volumes:
  redis-dev-volume: