services:
  nats:
    image: nats:2.10
    container_name: "nats"
    ports:
      - "4222:4222"
      - "8222:8222"

  redis:
    # image: redis:6-alpine
    image: redis/redis-stack:latest
    container_name: "redis"
    ports:
      - "7379:6379"
      - "8003:8001"
    volumes:
      - redis-volume:/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: "chat_server_dev"
    depends_on:
      - nats
      - redis
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - "./config.json:/app/config.json"
    environment:
      - AIR_ENV=dev
volumes:
  redis-volume: